# Generated by Django 4.2.1 on 2023-05-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='categoria',
            field=models.CharField(choices=[('TRANSITO', 'Trânsito'), ('COMIDAS', 'Comidas'), ('RELATOS', 'Relatos'), ('JOGOS', 'Jogos'), ('FUTEBOL', 'Futebol'), ('OUTROS', 'Outros')], max_length=20),
        ),
    ]
